# Rename this file to languages.toml to enable multilingual support
[en]
languageName = "English"
languagedirection = "ltr"
title = "Onid1's blog"
weight = 1

[fr]
languageName = "French"
languagedirecion = "ltr"
title = "Le blog d'Onid1"
weight = 2