name: Deploy to Github Pages

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

concurrency:
    group: "pages"
    cancel-in-progress: false

jobs:
    build:
        runs-on: ubuntu-latest

        permissions:
            # Give the default GITHUB_TOKEN write permission to commit and push the
            # added or changed files to the repository.
            contents: write

        steps:
            - uses: actions/checkout@v3

            - name: Cache Hugo resources
              uses: actions/cache@v3
              env:
                  cache-name: cache-hugo-resources
              with:
                  path: resources
                  key: ${{ env.cache-name }}

            - uses: actions/setup-go@v4
              with:
                  go-version: "^1.17.0"
            - run: go version

            - name: Setup Hugo
              uses: peaceiris/actions-hugo@v2
              with:
                  hugo-version: "latest"
                  extended: true

            - name: Build with Hugo
                env:
                # For maximum backward compatibility with Hugo modules
                    HUGO_ENVIRONMENT: production
                    HUGO_ENV: production
                run: |
                hugo \
                    --gc \
                    --minify \
                    --baseURL "${{ steps.pages.outputs.base_url }}/" 

            - name: Deploy 🚀
              uses: JamesIves/github-pages-deploy-action@v4
              url: ${{ steps.deployment.outputs.page_url }}
              with:
                  branch: gh-pages
                  folder: public
                  clean: true
                  single-commit: true
